version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            cd ..
            ls
            git clone https://github.com/polymonster/pmtech.git
