version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
      - image: gcc:7

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: build
          command: |
            sudo apt-get update
            sudo apt-get install libglew-dev
            apt-get download gcc-7.1
            sudo apt-get install gcc-7.1
            gcc --version
            cd ..
            git clone --recursive https://github.com/polymonster/pmtech.git
            cd repo
            python3 ../pmtech/tools/build.py -all
            cd build/linux
            make config=debug
            make confug=release
